"""Host-side RP86 transport constants and process exit codes."""

CANONICAL_GREETING = b"HELLO NEC V30"
CANONICAL_REPLY = b"HELLO OPENAI CODEX"
BOOTLOADER_REQUEST = b"RP86 BOOTLOADER\n"
BOOTLOADER_ACK = b"RP86 BOOTLOADER ACK"
REBOOT_REQUEST = b"RP86 REBOOT\n"
REBOOT_ACK = b"RP86 REBOOT ACK"
STATUS_REQUEST = b"RP86 STATUS\n"
STATUS_BEGIN = b"RP86 STATUS BEGIN"
STATUS_END = b"RP86 STATUS END"
HEARTBEAT_REPLY = b"PROCESSOR HEARTBEAT OK"
COMMAND_REPLY = b"PROCESSOR COMMAND OK"

USB_VID = 0xCAFE
USB_PID = 0x4011

PROCESSOR_NAMES = {
    "auto": "8086-CLASS PROCESSOR",
    "nec-v30": "NEC V30",
    "intel-8086": "INTEL 8086",
}

PASS_EXIT = 0
DEPENDENCY_EXIT = 3
TRANSPORT_EXIT = 4
VALIDATION_EXIT = 5
